# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-22 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_info',
            new_name='ContactInfo',
        ),
    ]
