# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='studyfield',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='section',
        ),
        migrations.RemoveField(
            model_name='material',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
