# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-26 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160826_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
