# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lecturer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'get_latest_by': 'pub_date'},
        ),
    ]
