# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-17 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160914_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='section',
            field=models.ManyToManyField(to='main.Section'),
        ),
    ]
