# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-27 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160921_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, upload_to=main.models.upload_path),
        ),
    ]
