# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-22 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160927_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='file1',
            field=models.FileField(blank=True, upload_to=main.models.static_path),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file2',
            field=models.FileField(blank=True, upload_to=main.models.static_path),
        ),
    ]
